# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl:
url: http://mmcwendy.info
date_format: "ordinal"
title: 毛毛虫_Wendy
subtitle: "Wendy's Personal Blog"
description: "Record ideas and knowledge"
keywords: Algorithm,Machine Learning(eg.Deep Learning),Data mining
timezone: Asia/Beijing
encoding: "utf-8"
side_bar_repo_limit: 5

# ---------------- #
#      Author      #
# ---------------- #
author: Wendy
organization: UESTC
organization_url: http://mmcwendy.info
github_username: DWJWendy
location: Chengdu, sichuan
email: dengwenjun818@gmail.com

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: 首页

  -
    href: /categories/
    label: 博客

  -
    href: /wiki/
    label: 维基

  -
    href: /links/
    label: 链接

  -
    href: /about/
    label: 关于

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
paginate: 8
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
gems:
    - jekyll-github-metadata
    - rouge
#     - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
#     - jekyll-mentions
collections:
    wiki:
        output: true
        permalink: /wiki/:path/

repository: DWJWendy/DWJWendy.github.io

# ---------------- # 
#      Comments    #
# ---------------- #
# support provider: disqus, gitment, gitalk
comments_provider: gitment
#comments_provider: disqus
#disque: https://disqus.com/by/wenjund/
# !!!重要!!! 请修改下面这些信息为你自己申请的
# !!!Important!!! Please modify infos below to yours
# https://disqus.com
disqus:
    username: wenjund
    
# https://imsun.net/posts/gitment-introduction/
gitment:
    owner: DWJWendy
    repo: blog-comments
    oauth:
        client_id: 5ca3b2576ef01cd69b30
        client_secret: d2a29efdba9f5f3ad0579de0ac2fbe8c300703c1
# https://github.com/gitalk/gitalk#install
gitalk:
    owner: DWJWendy
    repo: blog-comments
    clientID: 5ca3b2576ef01cd69b30
    clientSecret: d2a29efdba9f5f3ad0579de0ac2fbe8c300703c1
# 在使用其它评论组件时可点击显示 Disqus
lazy_load_disqus : false

# ---------------- #
#    Analytics     #
# ---------------- #
google:
    analytics_id: UA-80669434-1
